sudo: false
language: ruby

before_install:
  - gem install bundler -v 1.17.3
  - bundle install

env:
  - OPENCOURTS_DATABASE_USER=postgres OPENCOURTS_API_DATABASE_USER=postgres

before_script:
  - psql -c 'create database opencourts_test;' -U postgres
  - psql -c 'create database opencourts_api_test;' -U postgres
  - bundle exec rake db:test:load_schema
  - bundle exec rake db:seed

script:
  - bundle exec rspec spec

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: a9efd9926d7f81d2c8c378021cf007812837f5cada4d5b84f65aa84ecf8fd6f6
