opencourts: &opencourts
  adapter: postgresql
  encoding: utf8
  pool: 300
  host: localhost
  username: <%= ENV['OPENCOURTS_DATABASE_USER'] %>
  password: <%= ENV['OPENCOURTS_DATABASE_PASSWORD'] %>
  migrations_paths: db/opencourts_migrate

defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 300
  host: localhost
  username: <%= ENV['OPENCOURTS_API_DATABASE_USER'] %>
  password: <%= ENV['OPENCOURTS_API_DATABASE_PASSWORD'] %>

development:
  primary:
    <<: *defaults
    database: opencourts_api_development

  opencourts:
    <<: *opencourts
    database: opencourts_development

test:
  primary:
    <<: *defaults
    database: opencourts_api_test

  opencourts:
    <<: *opencourts
    database: opencourts_test

production:
  primary:
    <<: *defaults
    database: opencourts_api_production

  opencourts:
    <<: *opencourts
    database: opencourts_production
