opencourts: &opencourts
  adapter: postgresql
  encoding: utf8
  pool: 100
  host: 127.0.0.1
  username: <%= ENV['OPENCOURTS_DATABASE_USER'] %>
  password: <%= ENV['OPENCOURTS_DATABASE_PASSWORD'] %>

defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 100
  host: 127.0.0.1
  username: <%= ENV['OPENCOURTS_API_DATABASE_USER'] %>
  password: <%= ENV['OPENCOURTS_API_DATABASE_PASSWORD'] %>

opencourts_development:
  <<: *opencourts
  database: opencourts_development

opencourts_test:
  <<: *opencourts
  database: opencourts_test

opencourts_production:
  <<: *opencourts
  database: opencourts_production

development:
  <<: *defaults
  database: opencourts_api_development

test:
  <<: *defaults
  database: opencourts_api_test

production:
  <<: *defaults
  database: opencourts_api_production
